id = "hilrein"
name = "Hilrein"
version = "0.0.1"
schema_version = 1
authors = ["Hilrein (github.com/hilrein)"]
description = "My Theme for Zed"
repository = "https://github.com/hilrein/my-zed-extension"