id = "furina-vibe-theme"
name = "Furina Vibe Theme"
version = "0.1.2"
schema_version = 1
authors = ["Hilrein (github.com/hilrein)"]
description = "A dark blue theme inspired by Furina"
repository = "https://github.com/Hilrein/zed-Furina-vibe-theme"
